export * as ProcessesService from './processes'
export * as ProjectStepsService from './projectsteps'
export * as CountersService from './counters'
export * as AboutUsService from './aboutUs'
export * as LastProjectsService from './lastProjects'
export * as ProjectsService from './project'
export * as NewsService from './news'
